//Item "what it does" descriptions for the items-table hover tooltip.
//
//The stats endpoints (/items/stats, /heroes/:id/item-win-rates) carry no description
//text, and the rich src/data/items-detail.json is deliberately build-only (imported
//solely by the SSG detail route so it never enters the client bundle — see
//scripts/gen-item-catalog.mjs). The everywhere-loaded name+icon catalog
//(items-catalog.json / itemCatalog.ts) is kept lean on purpose too.
//
//So the hover tooltip gets its OWN lean, client-bundled map — just { item_id: desc }
//for the ~152 items that have a description — generated by the SAME
//scripts/gen-item-catalog.mjs. Import this module ONLY from the items-table island
//(ItemsTable.tsx); keep it out of itemCatalog.ts / apiClient so hero pages, which
//share that everywhere-chunk, never pull the description text.
import descriptions from '../data/item-descriptions.json';

const DESCRIPTIONS = descriptions as Record<string, string>;

//Plain-text "what it does" for an item id, or null when the catalog has none
//(the tooltip then just shows the stats, as before).
export function itemDescription(id: number | null | undefined): string | null {
  return id == null ? null : (DESCRIPTIONS[String(id)] ?? null);
}
