//Item metadata fallback catalog.
//
//The stats endpoints /items/stats and /heroes/:id/item-win-rates return
//item_name and icon_url as null — the backend doesn't join item metadata there
//the way it does for /heroes and /items/modifiers. Left as-is the items table
//shows "Item 7409189" labels over blank monogram tiles, and GuideLiveStats
//(which matches referenced items BY NAME) can never match anything.
//
//This catalog — generated by scripts/gen-item-catalog.mjs from the deadlock-api
//assets service — resolves item_id -> { name, icon } so items render with their
//real name and CDN icon. The live API value ALWAYS wins; the catalog only fills a
//null, so if the backend later starts serving item_name/icon_url this layer
//silently becomes a no-op. Items with no CDN art keep GameIcon's monogram fallback.
import catalog from '../data/items-catalog.json';
import { resolveAsset } from './assets';

//Internal/unreleased tuning items — the only /items entries (3 of 251) with no shop icon and 0 recorded matches; Valve never ships them in the shop, so they stay out of the public buildable-item catalog (task ranklock-items-assets-fix).
export const INTERNAL_ITEM_IDS = new Set<number>([4284855775, 3449296332, 2861048274]);
export function isPublicItem(id: number | null | undefined): boolean {
  return id == null || !INTERNAL_ITEM_IDS.has(id);
}

export interface ItemMeta {
  name: string;
  icon: string | null;
}

const CATALOG = catalog as Record<string, ItemMeta>;

export function itemMeta(id: number | null | undefined): ItemMeta | undefined {
  return id == null ? undefined : CATALOG[String(id)];
}

//Any row that carries item_id plus the two nullable metadata fields (ItemStat,
//HeroItemWinRate). Kept structural so a new item-bearing shape works without edits.
type ItemMetaRow = { item_id: number | null; item_name?: string | null; icon_url?: string | null };

//Fill item_name/icon_url from the catalog when the API left them null. Returns a
//new object; a row whose id isn't in the catalog is returned unchanged.
export function enrichItemMeta<T extends ItemMetaRow>(row: T): T {
  const meta = itemMeta(row.item_id);
  if (!meta) return row;
  return {
    ...row,
    item_name: row.item_name ?? meta.name,
    //Route the winning icon (live API value or catalog fallback) through the
    //swappable asset base so item icons cut over with everything else.
    icon_url: resolveAsset(row.icon_url ?? meta.icon),
  };
}

export function enrichItems<T extends ItemMetaRow>(rows: T[]): T[] {
  return rows.map(enrichItemMeta);
}
